# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

#[build]
#command = "npm run build:preview"
#publish = "public"

#[build.environment]
#GO_VERSION = "1.20.5"

[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.119.0"

[context.production]
command = "npm run build:production"

[context.production.environment]
HUGO_ENV           = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.119.0"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from   = "/npmjs/*"
to     = "/npmjs/"
status = 200